// =============================================================================
// Module: chaos.bicep
// Description: Chaos Studio Target, Capabilities, and Experiment definitions
//              for injecting CPU Pressure & Memory Pressure into a Linux VM.
// =============================================================================

@description('Azure region for deployment')
param location string

@description('Resource name prefix')
param prefix string

@description('Target VM name')
param vmName string

@description('Client ID of the User-Assigned Managed Identity')
param chaosIdentityClientId string

// ---------------------------------------------------------------------------
// Existing VM reference (for scope bindings)
// ---------------------------------------------------------------------------
resource targetVm 'Microsoft.Compute/virtualMachines@2024-07-01' existing = {
  name: vmName
}

// ---------------------------------------------------------------------------
// Chaos Studio Target (Agent-based)
// agentProfileId is auto-generated by the service and returned as an output.
// ---------------------------------------------------------------------------
resource chaosTarget 'Microsoft.Chaos/targets@2024-01-01' = {
  name: 'Microsoft-Agent'
  scope: targetVm
  properties: {
    identities: [
      {
        type: 'AzureManagedIdentity'
        clientId: chaosIdentityClientId
        tenantId: tenant().tenantId
      }
    ]
  }
}

// ---------------------------------------------------------------------------
// Chaos Capabilities – CPU Pressure
// ---------------------------------------------------------------------------
resource cpuCapability 'Microsoft.Chaos/targets/capabilities@2024-01-01' = {
  parent: chaosTarget
  name: 'CPUPressure-1.0'
}

// ---------------------------------------------------------------------------
// Chaos Capabilities – Physical Memory Pressure
// ---------------------------------------------------------------------------
resource memoryCapability 'Microsoft.Chaos/targets/capabilities@2024-01-01' = {
  parent: chaosTarget
  name: 'PhysicalMemoryPressure-1.0'
}

// ---------------------------------------------------------------------------
// Chaos Capabilities – Network Disconnect
// ---------------------------------------------------------------------------
resource networkCapability 'Microsoft.Chaos/targets/capabilities@2024-01-01' = {
  parent: chaosTarget
  name: 'NetworkDisconnect-1.2'
}

// ---------------------------------------------------------------------------
// Chaos Capabilities – Stop Service
// ---------------------------------------------------------------------------
resource stopServiceCapability 'Microsoft.Chaos/targets/capabilities@2024-01-01' = {
  parent: chaosTarget
  name: 'StopService-1.0'
}

// ---------------------------------------------------------------------------
// Chaos Agent VM Extension
// The agent must be installed on the VM for agent-based faults to work.
// Uses the agentProfileId auto-generated by the Chaos Target resource.
// ---------------------------------------------------------------------------
resource chaosAgentExtension 'Microsoft.Compute/virtualMachines/extensions@2024-07-01' = {
  parent: targetVm
  name: 'ChaosAgent'
  location: location
  properties: {
    publisher: 'Microsoft.Azure.Chaos'
    type: 'ChaosLinuxAgent'
    typeHandlerVersion: '1.0'
    autoUpgradeMinorVersion: true
    enableAutomaticUpgrade: true
    settings: {
      profile: chaosTarget.properties.agentProfileId
      'auth.msi.clientid': chaosIdentityClientId
    }
  }
}

// ---------------------------------------------------------------------------
// Experiment 1 – CPU Pressure (95 % for 10 minutes)
// ---------------------------------------------------------------------------
resource cpuExperiment 'Microsoft.Chaos/experiments@2024-01-01' = {
  name: '${prefix}-cpu-pressure-exp'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    selectors: [
      {
        id: 'selector1'
        type: 'List'
        targets: [
          {
            id: chaosTarget.id
            type: 'ChaosTarget'
          }
        ]
      }
    ]
    steps: [
      {
        name: 'step1-cpu-pressure'
        branches: [
          {
            name: 'branch1'
            actions: [
              {
                type: 'continuous'
                name: 'urn:csci:microsoft:agent:cpuPressure/1.0'
                duration: 'PT10M'
                parameters: [
                  {
                    key: 'pressureLevel'
                    value: '95'
                  }
                ]
                selectorId: 'selector1'
              }
            ]
          }
        ]
      }
    ]
  }
  dependsOn: [
    cpuCapability
    chaosAgentExtension
  ]
}

// ---------------------------------------------------------------------------
// Experiment 2 – Memory Pressure (90 % for 10 minutes)
// ---------------------------------------------------------------------------
resource memoryExperiment 'Microsoft.Chaos/experiments@2024-01-01' = {
  name: '${prefix}-memory-pressure-exp'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    selectors: [
      {
        id: 'selector1'
        type: 'List'
        targets: [
          {
            id: chaosTarget.id
            type: 'ChaosTarget'
          }
        ]
      }
    ]
    steps: [
      {
        name: 'step1-memory-pressure'
        branches: [
          {
            name: 'branch1'
            actions: [
              {
                type: 'continuous'
                name: 'urn:csci:microsoft:agent:physicalMemoryPressure/1.0'
                duration: 'PT10M'
                parameters: [
                  {
                    key: 'pressureLevel'
                    value: '90'
                  }
                ]
                selectorId: 'selector1'
              }
            ]
          }
        ]
      }
    ]
  }
  dependsOn: [
    memoryCapability
    chaosAgentExtension
  ]
}

// ---------------------------------------------------------------------------
// Experiment 3 – Service Stop (nginx for 5 minutes)
// ---------------------------------------------------------------------------
resource serviceStopExperiment 'Microsoft.Chaos/experiments@2024-01-01' = {
  name: '${prefix}-stop-nginx-exp'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    selectors: [
      {
        id: 'selector1'
        type: 'List'
        targets: [
          {
            id: chaosTarget.id
            type: 'ChaosTarget'
          }
        ]
      }
    ]
    steps: [
      {
        name: 'step1-stop-nginx'
        branches: [
          {
            name: 'branch1'
            actions: [
              {
                type: 'continuous'
                name: 'urn:csci:microsoft:agent:stopService/1.0'
                duration: 'PT5M'
                parameters: [
                  {
                    key: 'serviceName'
                    value: 'nginx'
                  }
                ]
                selectorId: 'selector1'
              }
            ]
          }
        ]
      }
    ]
  }
  dependsOn: [
    stopServiceCapability
    chaosAgentExtension
  ]
}

// ---------------------------------------------------------------------------
// Outputs
// ---------------------------------------------------------------------------
output cpuExperimentId string = cpuExperiment.id
output cpuExperimentName string = cpuExperiment.name
output cpuExperimentPrincipalId string = cpuExperiment.identity.principalId
output memoryExperimentId string = memoryExperiment.id
output memoryExperimentName string = memoryExperiment.name
output memoryExperimentPrincipalId string = memoryExperiment.identity.principalId
output serviceStopExperimentId string = serviceStopExperiment.id
output serviceStopExperimentName string = serviceStopExperiment.name
output serviceStopExperimentPrincipalId string = serviceStopExperiment.identity.principalId
